//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHV
{
    using System;
    using System.Collections.Generic;
    
    public partial class hocvien
    {
        public string mshv { get; set; }
        public string tenhv { get; set; }
        public string hinh { get; set; }
    }
}
