//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHV
{
    using System;
    using System.Collections.Generic;
    
    public partial class diemthi
    {
        public string mshv { get; set; }
        public string msmh { get; set; }
        public string diem { get; set; }
    
        public virtual lylich lylich { get; set; }
        public virtual monhoc monhoc { get; set; }
    }
}
